/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';

export const GET_SITEINFO_START = 'GET_SITEINFO_START';
export const GET_SITEINFO_SUCCESS = 'GET_SITEINFO_SUCCESS';
export const GET_SITEINFO_ERROR = 'GET_SITEINFO_ERROR';
